# Generated by Django 5.0.4 on 2024-05-02 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='servicios.servicio'),
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=30)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='servicios.servicio')),
            ],
        ),
    ]
